#!/bin/bash
set -evx 

startyear=$1
endyear=$2
name=$3


 for ((year=${startyear}; year <= ${endyear}; year++)); do
 		let ny=year+1
	
 		ncra ${name}-${year}-0[2-9]-01.nc ${name}-${year}-1[01]-01.nc ${name}-${ny}-01-01.nc ${name}_${year}.nc -O
 		 rm -f ${name}_${year}_smb.nc 
		 cdo merge -selvar,usurf ${name}_${year}.nc -ifthen -gtc,10 -selvar,thk  ${name}_${year}.nc -selvar,climatic_mass_balance,csurf ${name}_${year}.nc ${name}_${year}_smb.nc
 		files="${files} ${name}_${year}_smb.nc" 
 done
	 
ncra ${files} ${name}_smb_${startyear}_${endyear}.nc -O
ncks -A -v x,y ${name}-${year}-01-01.nc ${name}_smb_${startyear}_${endyear}.nc
