#!/usr/bin/env python

from netCDF4 import Dataset
#import matplotlib.pyplot as mpl
import numpy as np
import sys
from argparse import ArgumentParser
from numpy.lib.polynomial import polyfit
import os
import flo_utils as fu
import shutil


import scatter_elas
fname = "max_elas_no_7_min_5_no_year.dat"
ofname = "%s.nc"%fname[:-4]
elas, means, errpos, errneg = scatter_elas.read_file(fname)

shutil.copyfile("Juneau_Icefield.nc", ofname)

tsl=Dataset(ofname, "r+")

var=tsl.variables["output_mask"]

lfield=var[:].reshape(var.size)
print means.keys()

newfield=np.array([means.get("RGI32-01.%05d"%x, -1) for x in lfield  ],dtype=var.dtype).reshape(var.shape)
var[:]=newfield
tsl.close()
