#!/bin/bash

set -evx

for x in $@ ;  do
    grep wfl $x/fort.7  | awk '{print $1, $3, $4, $3-$4, $6, $7, $6-$7}' > $x/lat_HFL-G_HFL-A_HFL-P_WFL-G_WFL-A_WFL-P.dat
    awk '{print $1, $7}' $x/lat_HFL-G_HFL-A_HFL-P_WFL-G_WFL-A_WFL-P.dat > $x/WFL_PAC.dat
done
