#!/usr/bin/env python

import osr
inSpatialRef = osr.SpatialReference() # orig projection
inSpatialRef.ImportFromEPSG(3338) # Alaska Albers
outSpatialRef = osr.SpatialReference() # target projection
outSpatialRef.ImportFromEPSG(4326) # WGS 1982
coordTransform = osr.CoordinateTransformation(inSpatialRef, outSpatialRef) # create converter
# inSpatialRef.ExportToPrettyWkt() # display information on orig projection
# outSpatialRef.ExportToPrettyWkt() 
#coordTransform.TransformPoint(1.4e6,1e6) # transform a sample point from AA to WGS

