#!/usr/bin/env python
import sys

namedict ={"F0065" : 'REF',
           "F0096" : 'res$\downarrow$', "F0070" : 'res$\uparrow$',
           "F0071" : 'smelt$\uparrow$', "F0074" : 'smelt$\downarrow$',
           "F0072" : 'imelt$\uparrow$', "F0075" : 'imelt$\downarrow$',
           "F0073" : 'simelt$\uparrow$', "F0076" : 'simelt$\downarrow$',
           "F0077" : 'thick,slow', "F0078" : 'thin,fast',
           "F0079" : 'sliding$\uparrow$', "F0080" : 'sliding$\downarrow$',"F0095" : 'no sliding',
           "F0081" : 'thick', "F0082" : 'thin',
           "F0083" : 'slow', "F0084" : 'fast',
           "F0085" : 'grad$\downarrow$', "F0086" : 'grad$\uparrow$', "F0087": 'no grad',
           "F0090" : 'S2010', 
           "F0091" : 'S2040',
           "F0092" : 'S2070', 
           "F0093" : 'S2099',  
           "F0088":"R2010",  
           "F0099":"R2070",  
           "F0100":"R2040"
           } 

inverse={namedict[x]:x for x in namedict.keys()}


def main(argv):
    for x in argv[1:]:
        print namedict.get(x,inverse.get(x,"NOT FOUND"))


  
if __name__ == "__main__":
    main(sys.argv)

