#!/usr/bin/env python


import netCDF4 as nc
import matplotlib.pylab as mpl
import sys
import flo_utils as fu
from argparse import ArgumentParser
import shutil
import numpy as np


def run_pism():
  filename_start = "adjust_test"
  ## repeat until dead:
  for counter in xrange(38,100) :
    # run pism 
    input_file = filename_start + "_input_%04i.nc"%(counter)
    output_file = filename_start + "_output_%04i.nc"%(counter)
    options_geloet = " -c run_pism_flo-binary.conf -y 10  --force_to_thk topo_hand.nc --force_to_thk_alpha 0.2  --no-ssa "
    fu.qo("run_pism -i %s -o %s %s"%(input_file, output_file, options_geloet))

    # copy the output file
    input_file = filename_start + "_input_%04i.nc"%(counter+1)
    shutil.copyfile(output_file, input_file)
    # call adjust_topg
    fu.qo("adjust_topg %s -s state.nc"%(input_file))
    shutil.copyfile("state.nc", "state_" + input_file)


    
def parse_args():
  parser = ArgumentParser()
  parser.description = "compare slopes of two variables from two files"
#  parser.add_argument("FILES", nargs=1)
  parser.add_argument("-v", "--verbose", 
                    help='''Be verbose''', action="store_true")
  # parser.add_argument("-r", "--reference", 
  #                      help='''file with reference values''', default="reference.nc") 
  # parser.add_argument("-s", "--state", 
  #                      help='''file with reference values''', required = True) 
  # parser.add_argument("-b", "--var_b", 
  #                    help='''variable b''', default="data")
  options = parser.parse_args()
  return options


def main():
  options = parse_args()
  if options.verbose:
    print (dir(options))
    print options.FILES
    fu.debug=True

  run_pism()
      
if __name__ == "__main__":
    main()
